### ISSUE TITLE
Question about VMAT branches

### ISSUE THREAD

**Issue by chh105** [e0404/matRad#499]
I had a question about the various VMAT branches (i.e. dev_VMAT_merge, dev_VMAT, dev_4DVMAT, etc.). I'm hoping to pick one to use for a research project and was wondering which of these branches would be the best option. It seems the dev_4DVMAT one is the most up-to-date (according to what I was told in a previous github post), though the file structure is completely different from the master branch of matRad. Other branches like dev_VMAT_merge have similar file structures to the master branch but may not be as up-to-date (?). 

Is there a working branch for VMAT that you guys would recommend? As always, thanks for your help and advice!

**Comment by eric11210** [comment]
Indeed dev_4DVMAT is the most up-to-date branch. As you point out, the file and code structure is quite different than the master, since I started working on it a few years back and unfortunately did not keep it up to date with the master.

I believe that the dev_VMAT_merge branch is still a complete implementation of VMAT, but there were some tweaks that I made to the optimization algorithm in dev_4DVMAT that aren't reflected in dev_VMAT_merge.

Hopefully you can follow along with what I said, and make a decision based on that information. If you're doing a research project and need something now, then I think I would suggest dev_VMAT_merge for perhaps a cleaner and more consistent implementaiton.

I would like to (finally!) merge all of these branches into one, and then finally into the master. Unfortunately I can't give you a timeframe on this. @wahln, maybe it's time to take a look at this again?

**Comment by chh105** [comment]
Thanks for the quick replies and I hope Eric's residency is going well. As a follow up question, do you have any recommendations on what settings to use for VMAT that may be more stable. For example, would the settings in this file be a good starting point? 
[example from dev_VMAT_merge](https://github.com/e0404/matRad/blob/dev_VMAT_merge/examples/matRad_example8_photonsVMAT.m)

**Comment by eric11210** [comment]
Thanks @chh105!

Yes, that would be a good place to start (that was the intention behind that script 😄).

@wahln, what weird results do you mean? Is it related to the optimization, or something else?

**Comment by wahln** [comment]
on the dev_VMAT_merge, there are some things going wrong in the aperture optimization (see my comments in #377). It does not produce the same results as the dev_VMAT at the moment, and is (with high certainty) my fault so far. Will check it out again soon, I am quite confident I can figure out the remaining issues.

**Comment by chh105** [comment]
Hi @wahln, just wanted to get some help with running the dev_vmat_merge branch. I've [linked](https://github.com/chh105/matRad_vmat_crash) the modified prostate phantom (with various constraints/objs) and the photon vmat script. When I tried running the photon vmat script, it would crash my matlab instance whenever it attempted to run DAO. I was wondering if you had experienced similar issues or had any insights as to why this was happening

**Comment by chh105** [comment]
@wahln (sorry, I don't mean to spam): After doing more testing, I found that my matlab will crash whenever DAO is run with constraints (not just in the vmat case). I've [linked](https://github.com/chh105/matRad_vmat_crash/tree/main/vmat_crashes) the DAO example script and the prostate phantom (with various constraints) to reproduce the crash. Is this something that you've experienced as well, and if so, is there some workaround to incorporate constraints while performing DAO? Thanks for your help

**Comment by wahln** [comment]
Actually that shouldn't happen, thanks for reporting this bug. Will try to look at it asap, but it might take a few days.

**Comment by chh105** [comment]
Sure, I just wanted to make sure it wasn't only happening on my end. Thanks for taking the time to look into it.

**Comment by chh105** [comment]
Just as a quick update, I tried switching the optimizer to fmincon's interior point version instead of IPOPT and got the following error trace:


```
Index exceeds the number of array elements (914).

Error in matRad_OptimizationProblemDAO/matRad_constraintJacobian (line 101)
        .*
        jacob_dos_bixel(:,apertureInfo.bixelIndices(apertureInfo.totalNumOfShapes+1:apertureInfo.totalNumOfShapes+apertureInfo.totalNumOfLeafPairs*2))
        ./ ...

Error in matRad_OptimizerFmincon/fmincon_nonlconWrapper (line 105)
            cJacob = optiProb.matRad_constraintJacobian(x,dij,cst);

Error in matRad_OptimizerFmincon>@(x)obj.fmincon_nonlconWrapper(x,optiProb,dij,cst) (line 72)
                @(x) obj.fmincon_nonlconWrapper(x,optiProb,dij,cst),...

Error in fmincon (line 650)
      [ctmp,ceqtmp,initVals.gnc,initVals.gnceq] = feval(confcn{3},X,varargin{:});

Error in matRad_OptimizerFmincon/optimize (line 67)
            [obj.wResult,fVal,exitflag,info] = fmincon(@(x)
            obj.fmincon_objAndGradWrapper(x,optiProb,dij,cst),...

Error in matRad_directApertureOptimization (line 126)
optimizer = optimizer.optimize(apertureInfo.apertureVector,optiProb,dij,cst);

Error in matRad_example3_photonsDAO (line 102)
resultGUI = matRad_directApertureOptimization(dij,cst,resultGUI.apertureInfo,resultGUI,pln);

Caused by:
    Failure in initial nonlinear constraint function evaluation. FMINCON cannot continue.

```
This error is occurring in the dev_VMAT_merge branch. I don't think that this error occurs for previous branches (i.e. dev_VMAT, master, etc.), but I wasn't able to test them fully due to errors in the example scripts.

**Comment by wahln** [comment]
Thanks for the error messsage. From that and some other quick tests I think that the error is caused by a mistake in how the leaf constraints are joined with the dose constraints in the jacobian computation. Will get to the bottom of this soon.

**Comment by wahln** [comment]
I have started to look into the issue on the master branch, where using additional constraints did not work. I think I fixed it in #506. Will check this out in connection to the VMAT issues next.

**Comment by chh105** [comment]
Great, thank you so much! As far as I can tell, those changes fixed crash/error during DAO. I was also able to run through [VMAT example script #8](https://github.com/chh105/matRad-hotfixes-daoWithConstraints) without any crashes.

**Comment by chh105** [comment]
As another quick update, I just realized that the fixes were applied to the master branch which doesn't support vmat (so running example 8 was just running DAO with many angles and not vmat). Sorry if that causes any confusion. 

I just tried running the dev_VMAT_merge branch with the updated matRad_constraintFunctions.m and matRad_getJacobianStructure.m files. It seems to still crash with the same error trace as before. I'm happy to continue testing if it helps!

**Comment by wahln** [comment]
Yeah, I guess that I need to merge this carefully into the dev_VMAT_merge and also make some adaptations towards VMAT. I will start doing this and aks for a test run from you as soon as I get something that seems to work. Thanks again.

**Comment by wahln** [comment]
First of all, thanks to you @chh105 . Your investigation of the VMAT behavior made me find some of the stuff that was wrong with the VMAT merge. I've updated the dev_VMAT_merge branch with my fixes for now, it should now at least run through with dose constraints. Maybe you want to check if this works as expected on your system, too. There's still something off in the VMAT direct aperture optimization. When I am optimizing without preconditioner, the solution makes sense but is far from "optimal" with the standard optimization settings. This is what you would expect, since it just converges too slowly without preconditioning. Turning the preconditioner on gives weird results. It has to do with some of the reorderings I did in the code. I will continue my investigations...

**Comment by wahln** [comment]
By the way: The problem was the jacobian computation, which had some old code in it and did not rely on the pre-computed beamlet/aperture jacobian like it is used in the gradient computation. This is the same issue for the original dev_VMAT branch.

**Comment by chh105** [comment]
@wahln Thanks again for the updates. Your explanation about the jacobian computation makes sense and is consistent with the errors I was getting. I'm really excited to try out the fixes, and I'll let you know how it goes!

**Comment by chh105** [comment]
If it helps, here is the dvh after running VMAT DAO. The prescription dose was 2.267 Gy, but the value for D95% was 0.0065

![image](https://user-images.githubusercontent.com/56953865/117348082-a26ad000-ae5e-11eb-9ed5-7a70516f8a81.png)

**Comment by eric11210** [comment]
Looks to me like the Jacobi preconditioning factors are not being used correctly in the code. These represent a factor between actual aperture weights and the elements in the optimization vector corresponding to those weights. They can easily get mixed up (probably due to the way I coded it...)

**Comment by wahln** [comment]
Yes that is most likely the reason. I reorganized some parts of the code to make some things possible within the new optimization structure, but I may have jumped to conclusions in some parts. Two questions: 
- @chh105 Did this DVH result from  optimization with some dose constraint or without? 
- @eric11210 Is there anything big that would hinder the use of the preconditioner with DAO only (without VMAT?) Working on this might be a good setting for me to check the basic functionality and understand the implementation a bit more.

**Comment by chh105** [comment]
@wahln The DVH result was from optimization with DVH constraints, min/max dose constraints, and EUD constraints ([prostate phantom with constraints](https://github.com/chh105/matRad_vmat_crash/blob/main/vmat_crashes/PROSTATE_CONSTRAINTS_TEST.mat))

**Comment by eric11210** [comment]
@wahln I intended the preconditioner to be used for DAO generally, i.e. not restricted to VMAT only. I did do some functionality testing on the original code without VMAT, so it should work.

**Comment by wahln** [comment]
I think I found the bug. On the one hand, it was a stupid merging mistake by me - I accidentally omitted the `dij.scaleFactor` coming from the preconditioner in the backprojection. On the other hand, I am not sure if I want the scaling factor to be as intrusive, i.e., it being written into the dij, because it is actually a part of optimization and not of the dij itself. But maybe, that's the smoothest way - I have to think about it... for now, the changes are on the dev_VMAT_merge branch, and I think now we have a merged version that is running correctly in the default setup, at least.

**Comment by eric11210** [comment]
@wahln That's probably it. Agreed, it makes more sense to separate it from the dij and put it with an optimization structure. I think I did it this way since this factor was always multiplying elements in the dij. But it can lead to confusion, because it's not clear from the name and location exactly what it's doing.

**Comment by chh105** [comment]
I ran some tests with the updated dev_VMAT_merge on the same prostate phantom with constraints:

- VMAT ran without crashing, but the obj function, constraint violation, etc. during DAO were still high. I got the following DVH which shows improvements over the previous one but still violates the various constraints.
![vmat_dvh_debug_2](https://user-images.githubusercontent.com/56953865/117555825-51520c00-b017-11eb-9c9c-52d53fca30ec.jpg)

- Regular DAO (example script 3) crashed with the same error trace as before:
```
Index exceeds the number of array elements (1196).

Error in matRad_OptimizationProblemDAO/matRad_constraintJacobian (line 103)
        .*
        jacob_dos_bixel(:,apertureInfo.bixelIndices(apertureInfo.totalNumOfShapes+1:apertureInfo.totalNumOfShapes+apertureInfo.totalNumOfLeafPairs*2))
        ./ ...

Error in matRad_OptimizerFmincon/fmincon_nonlconWrapper (line 105)
            cJacob = optiProb.matRad_constraintJacobian(x,dij,cst);

Error in matRad_OptimizerFmincon>@(x)obj.fmincon_nonlconWrapper(x,optiProb,dij,cst) (line 72)
                @(x) obj.fmincon_nonlconWrapper(x,optiProb,dij,cst),...

Error in fmincon (line 650)
      [ctmp,ceqtmp,initVals.gnc,initVals.gnceq] = feval(confcn{3},X,varargin{:});

Error in matRad_OptimizerFmincon/optimize (line 67)
            [obj.wResult,fVal,exitflag,info] = fmincon(@(x)
            obj.fmincon_objAndGradWrapper(x,optiProb,dij,cst),...

Error in matRad_directApertureOptimization (line 130)
optimizer = optimizer.optimize(apertureInfo.apertureVector,optiProb,dij,cst);

Error in matRad_example3_photonsDAO (line 103)
resultGUI = matRad_directApertureOptimization(dij,cst,resultGUI.apertureInfo,resultGUI,pln);

Caused by:
    Failure in initial nonlinear constraint function evaluation. FMINCON cannot continue.
```

**Comment by wahln** [comment]
Thanks again @chh105 for your enduring testing efforts!
So I could confirm the DAO problem, which was due to a change in the dimensionality in the `bixelWeight` variable. I pushed an update and now it should work. However, so far it only seems to work reliably with fmincon. WIth IPOPT, there is some mismatch between the pre-computed jacobian structure and the evaluation, i.e., there are elements filled with non-zero values during jacobian computation that were defined as zero when setting up the structure that is used by IPOPT. Still need to check figure out why.
I could not confirm the continuing VMAT problem - what dose constraints are you using? It might just be, that the problem is hardly feasible.

**Comment by chh105** [comment]
As a quick update, I just verified that both VMAT DAO and regular DAO for the dev_VMAT_merge branch run without crashing. It seems that there are constraint violation issues when performing VMAT DAO and regular DAO. I've saved two configurations of the prostate phantom as ".mat" files in order to reproduce these issues.

- [PROSTATE_CONSTRAINTS_TEST.mat](https://github.com/chh105/matRad_vmat_crash/blob/main/vmat_crashes/PROSTATE_CONSTRAINTS_TEST.mat) contains EUD constraints, DVH constraints, and min/max dose constraints. The FMO problem for this configuration was feasible, so I'm hoping that DAO would also be feasible
- [PROSTATE_SIMPLE_CONSTRAINTS.mat](https://github.com/chh105/matRad_vmat_crash/blob/main/vmat_crashes/PROSTATE_SIMPLE_CONSTRAINTS.mat) contains only quadratic objectives and a DVH constraint (D95% = prescription dose). The FMO problem was also feasible here, but again DAO appeared to be infeasible.

**Comment by wahln** [comment]
I wouldn't say that feasibility can be easily assumed for DAO/VMAT when FMO is feasible. The segmentation into shapes puts quite some restrictions into how doses can be achieved. 
But it should work for simple constraints (at least that's how I tested it) - for example a single lower dose bound in the PTV could be achieved by scaling up a shape weight. Will need to find some time to do some more in-depth tests...

**Comment by chh105** [comment]
That makes sense. Thanks for the explanation and for looking into this issue

**Comment by chh105** [comment]
I had some time today to run some more tests on the dev_VMAT_merge branch. From what I can tell, DAO with only objectives seems to work fine. However, DAO with dose objectives & constraints does not work as intended, even with simple constraints. 

The first DVH below is from DAO with quadratic objectives for the ptv and body (seems to work fine):
![image](https://user-images.githubusercontent.com/56953865/118339715-87d3cf00-b4ce-11eb-9db9-9368e7af1755.png)

The second DVH below is from DAO with quadratic objectives for the ptv and body, as well as a DVH constraint for the ptv (not working):
![image](https://user-images.githubusercontent.com/56953865/118339730-8f937380-b4ce-11eb-9732-78b16f633fc7.png)

I'll try repeating these tests on the master branch to see if it's just an issue with the dev_VMAT_merge branch

**Comment by chh105** [comment]
Hi @wahln and @eric11210 , hope everything is going well! Just wanted to check in with you guys since I haven't heard back in a couple weeks.

I tested FMO, FMO+DAO, and VMAT (FMO+DAO) with very simple DVH constraints (D95 > prescription dose). All of these tests in the dev_VMAT_merge branch had very large constraint violations. It seems to me that there is an issue with the dose constraints implementation only in the dev_VMAT_merge branch. These issues did not occur for the master branch, so I'm thinking that there were some changes made in this particular branch that are causing dose constraints not to work properly. When you have the time, would it be possible to get some more help with this issue?

**Comment by chh105** [comment]
Hi again! I realize you both are very busy, so I'll try to keep it brief. I just had a couple conceptual questions that I'm hoping to get answered.

It seems to me that the main branch of matRad supports FMO, leaf sequencing, and DAO. The dev branch, however, has weird issues when performing optimization with dose constraints. Would it be a bad idea to perform FMO -> sequencing -> DAO manually with angles spaced every 2 degrees instead of using the dev_VMAT_merge branch? Conceptually, what would be the main differences between manually running these components (FMO, sequencing, DAO) and running the dev_VMAT_merge branch?

**Comment by wahln** [comment]
Hi! 
Sorry for keeping it quiet for quite some time, but I will get back to looking into the VMAT branch within the next days.

I guess there is still some issue in the constraint jacobian computation. I think I will try to copy the implementation that's on the master branch to validate this and hopefully figure out what is going wrong. For the VMAT set-up, I recently tested min/max constraints which seemed to work on a simple phantom set-up after many iterations (the convergence was slow and somewhat weird). For DAO without VMAT, there still seem to be issues with IPOPT (related to the structure of the jacobian, which indicates the mentioned issues in constraint jacobian), but the solution seemed sound with fmincon. This whole variation in behavior that I induced with my merge efforts makes it really difficult to pin down the issues, sorry...

While I think that @eric11210 would be able to give you a more detailed answer, in principle, that is also the workflow that is implemented in the VMAT branch. However, doing this without adaptation on the master branch will probably end up in non-deliverable VMAT plans, since you need to factor in maximum leaf speed and also make sure you have connected, single shapes for DAO. But if you find a workaround, you might get something.

**Comment by eric11210** [comment]
@wahln What you've said is correct. @chh105 if you perform FMO, sequencing, DAO without the VMAT option turned on, but an eg 2 degree angle spacing, essentially what you'll get is a very dense IMRT plan, with many apertures at each angle. Part of what the VMAT option does is take only a single aperture for each angle, and then optimize that one (and then also force max leaf speed constraints etc.)

**Comment by chh105** [comment]
Thank you both for the explanations. That helps to resolve my previous confusion with the different approaches.  

For the VMAT issues, I completely understand that it's very tricky to debug, and I'm grateful that you haven't given up on it. If you need me to run some tests or help out in some way, I'm would be happy to do so

**Comment by chh105** [comment]
Hi again, I just wanted to post an update about a potentially related issue that I've found. I tried running FMO with a single quadratic objective for the PTV for the prostate phantom with 5-9 beams on the latest matRad branch. These results worked as expected (i.e. the PTV dose volume histogram falls off at the reference dose).

![single_obj_issue1](https://user-images.githubusercontent.com/56953865/127722277-88cc02b8-a906-4d32-8c40-838acf0e8d18.jpg)

If I then run the same FMO problem (single quadratic objective for the PTV) with a larger number of beams (~30 beams to match the number used in VMAT), I get the issue shown in the second picture where there seems to be a large amount of PTV inhomogeneity. Strangely, the final objective function value for the ~30 beam scenario was much lower than the final objective function value for the ~5-9 beam scenarios. Yet, the ~30 beam dose distribution shows much larger deviations from the reference dose

![single_obj_issue](https://user-images.githubusercontent.com/56953865/127721969-89b62310-467f-4d14-92e1-4bb1698fee71.jpg)

Could this be related to the issues with the VMAT branch, since that branch also uses a large number of beams for FMO?

**Comment by wahln** [comment]
Thanks for conitnuing the investigation here. I didn't quite stick to the promise of looking more into the jacobian, but I hope I can do this in August. Few questions from my side:
- The optimizer was IPOPT?
- How big is the difference for the objective function value?
- The single objective was only on the PTV_68?
- what was the setting for the dose grid resolution?
- The latest matRad-branch was the current master? or the latest VMAT?

**Comment by chh105** [comment]
No worries, I was just trying to keep a log of the things I found while testing various branches. To answer your questions,

- Yes, IPOPT
- The obj value when using a smaller number of beams was around 1e-3 or 1e-4 and the obj value with a larger number of beams was around 1e-6 (ran IPOPT for the same number of iterations for all scenarios)
- Yes I only set an objective for ptv_68 just to test this optimization behavior
- I used the default setting of 5mm
- I used the [hotfixes/daoWithConstraints](https://github.com/e0404/matRad/tree/hotfixes/daoWithConstraints), which I think is pretty much the same as the latest master branch (?).

As another comment, I did some other tests with the dev_VMAT (not merge) branch, using only quadratic objectives without any constraints. I found that IPOPT converged very quickly (within 100 iterations) and the obj value plot continuously decreased. I think this is expected since using only quadratic objectives would make this a convex problem, but maybe I'm wrong about that. However, when testing quadratic objectives on the dev_VMAT_merge and hotfixes/daoWithConstraints branches, I was not getting the same convergence (the plot of the obj value had long intervals where the obj value would increase)

**Comment by wahln** [comment]
Thanks for the info!
What _might_ be the issue here (as a first guess) is the resampling of the grids between the ct and the 5mm dose grid. The dose grid (5mm in this case) is used for dose calculation and optimization. At the end, the dose will be interpolated/extrapolated to match the ct grid again, and the DVH will be evaluated on this grid. The problem here often lies in the downsampling of the cst masks to a worse resolution, which is done with nearest neighbors. So the optimization very homogeneously covers the PTV with that many beams (i.e., very low objective function value), but may create very large doses in the surrounding tissue, which in resampling to the ct grid gives the overdose inhomogeneity in the PTV of the original resolution.
Best way to test this is to set the dose calc resolution to the ct resolution.

I don't know if there would be a good solution to this resampling issue, I guess its something to live with when using too coarse grids. For dosimetric accuracy I would go with <= 3mm for the dose grid.

**Comment by chh105** [comment]
Hope everything is going well! As another update, I've been testing the dev_VMAT branch this time without any dose constraints. It seems that vmat works fine (as far as I can tell) for that branch. I'm currently trying to test vmat planning with multiple arcs, so I'm trying to modify the [gantry angle file](https://github.com/e0404/matRad/blob/dev_VMAT/matRad_VMATGantryAngles.m). What would be a good way to modify this file to incorporate additional arcs? (I'm assuming just adding additional angles to the pln structure would be a bad idea)

**Comment by chh105** [comment]
I had another quick question about using the vmat package (dev_VMAT). I'm currently trying to create a dual arc vmat plan where I created an initial vmat arc from -180 to 180 (4 degree spacing) and a second arc by copying the initial arc and offsetting by 362. I'm noticing that the memory usage is exceedingly large (on the order of 100GB of RAM). Is this typical for vmat planning, and would it be possible to reduce this memory usage somehow?

**Comment by eric11210** [comment]
Sorry for not replying to you about the double arc thing before. This is something that I have not implemented, so no guarantees that it works.

A couple of things:
1) To answer your memory question, the dij matrix is by far the element which consumes the most amount of memory. By creating a dual-arc VMAT plan in this way you are essentially doubling the memory requirements. This is probably unnecessary, since 4 degrees is usually enough resolution from the dose calculation point of view. You could probably "trick" the dose calculation functions into using the same dij elements for gantry 0 and gantry 360, for example.

2) If there was no additional modification to the code other than the offset, then technically there will be leaf speed constraints between the end of the first arc and the beginning of the second. This is not really required, but it is probably simplest to leave it as-is.

3) Did you do this offset for all of the angle sets? Eg gantryAngles, DAOGantryAngles, FMOGantryAngles?

**Comment by chh105** [comment]
Hi Eric, thanks for the quick reply. 

1. I think I understand the gist, but this seems quite tricky to do in practice.
2. For these leaf constraints, would this affect the plan quality or just lead to arbitrarily longer delivery time?
3. I tried adding this offset to all of the angle sets. 

Also I recently read through your paper on the continuous vmat apertures. I noticed that you used a DAOGantryAngle spacing of 4 and a gantryAngle spacing of 2 for head and neck cases. Would it be better to use that type of scheme (where you are doubling the vmat control points) instead of adding another arc?

**Comment by eric11210** [comment]
1. After thinking about it some more, I think it would be easiest to attack it from the other direction: the fluence. Something like (fluence @ gantry 0) = (fluence @ gantry 0) + (fluence @ gantry 360). This calculation would have to be done in each iteration of the optimizer. The gradient would also probably have to be modified somehow to account for this. Not sure how much digging into the code you've done. If you're stuck for how to do this let me know and I can give you some pointers.

2. Probably a little bit of both, but if I had to guess the impact would be minor. Basically both arcs would be linked, whereas in principle they could be independent, so you are removing a degree of freedom.

3. Okay good, I think that's the right way of doing it. I guess it probably wouldn't have run any other way.

To your last question, I think what you are doing is correct. If you only double the VMAT control points, you aren't creating an independent arc. Instead you're essentially just interpolating dose calculation control points from the optimization control points.

**Comment by chh105** [comment]
Thanks again for the thoughtful responses. I think for now I'll try messing around some more with the angle spacing, dose resolution, etc. to get things to fit into the capacity of my RAM.

Last thing is that I also noticed that sometimes FMO wouldn't converge when there were a large number of beams (i.e. the FMO spacing was set below 28 degrees to something like 14). Is this also something that you noticed before?

**Comment by eric11210** [comment]
Sounds good.

I don't think I ever went below ~28 degrees for the FMO spacing, so no I have not noticed that. I'm a little surprised by that, to be honest. What do you mean by not converging? Can you post an image of the obj function versus iteration?

**Comment by chh105** [comment]
Sure I'll try to reproduce the behavior and upload a picture tomorrow

**Comment by chh105** [comment]
Sorry for the delayed response. I've noticed that the issue when performing FMO might be caused by a mistake I made with the FMO angle sampling. Initially I was using an offset of 362 for all the angle sets (half of the dao and dose angle spacing). I think this places the FMO beams pretty much right on top of each other which may be an issue for the optimizer as the number of variables becomes large (large number of beams). I'm thinking it might be better to use an offset of 376 (360 + 2 + 14) for all of the angle sets.

**Comment by Boomxx07** [comment]
Hi all, in regards to the VMAT branches has the DICOM importer been updated to support VMAT DICOMs on any of them?

I'm currently using the dev_VMAT_merge branch and am having trouble importing a VMAT RT-Plan.

**Comment by wahln** [comment]
From our side, we haven't bothered with it yet. Maybe @eric11210 has tried something in this direction? I have just tried it myself with an old Raystation VMAT RTPlan and ran into some issues in matRad_importDicomSteeringPhotons.  I will check it out for a few mins, maybe the fixes are trivial for starters, otherwise @amitantony and I would be happy to assist with getting this to work if you are also open to contribute some investigative DICOM & coding work.

**Comment by chh105** [comment]
@Boomxx07 I can't remember if the dicom importer for the dev_VMAT_merge branch was working (it has been a while since I last tried). However, if you are ok with using an older branch like dev_VMAT, importing should be working for CT images and RT structures. There's also a function ([linked here](https://github.com/chh105/MetaPlanner/blob/main/matRad-dev_VMAT/misc/import_dicom_vmat.m)) that will import those dicoms for you if you specify the filepath, voxel size, beam width, etc.

**Comment by Boomxx07** [comment]
Hi both, thank you for your quick replies.

@wahln  I still don't seem to be able to import my RTPlans, specifically the issue appears to be in the same area where you put in the fix. The number of isocentre values in pln.propStf.isoCenter is 2 (I have a 2 beam VMAT RT Plan), however, the loop ~line 56 of matRad_importDicomSteeringPhotons is trying to go much higher (as each beem has 178 control points). I think line 82 of matRad_importDicomRTPlan would need to be modified to generate a bigger list of isocentres? What type of RTPlan were you importing with success?

@chh105 I had a look at dev_VMAT, however, I'm trying to import an RTPlan which and not just CT/Struct.

**Comment by wahln** [comment]
I imported a single-arc VMAT plan, which allowed me to just import all control points as gantry angles with the same isocenter.

First, as you said, I think the problem is that you seem to have two "arcs", right? my fix was only a workaround for single arc. Here we might need to look into `matRad_importDicomRTPlan.m` as well to better isolate the import of BeamSequence and ControlPointSequence for photons in case of VMAT. However, I don't have multi-arc VMAT DICOM RTPlan right now.

Second, I think the branch does not (yet) have the code infrastructure to support multiple arcs natively. The "easy way" forward would be to import them as to seperate `pln` & `stf` objects in matRad for the start, or just put all in one, assigning the correct isocenter in the import. 

Last, there should be no substantial difference in the DICOM importers on those branches.

**Comment by eric11210** [comment]
@Boomxx07 @wahln I did not do any work on the DICOM import when I implemented VMAT in matRad, so unfortunately there is no guarantee that anything will work correctly when trying to import a DICOM RT plan.

**Comment by Erhushenshou** [comment]
Hi Guys,
     Upon reading the posts above, is it right that we can do vmat in matrad right now? Is is released?

**Comment by wahln** [comment]
No it is not released, but you can try out the branch. dev_VMAT_merge.

**Comment by chh105** [comment]
Hi @wahln @eric11210 , I had a quick question about recalculating dose. Say that I have finished running DAO and my matlab workspace now has all of those relevant outputs (dij, resultGUI.apertureInfo, etc.). If I wanted to compute the contribution of each VMAT control point to the dose distribution, how would I go about doing so?

**Comment by eric11210** [comment]
I would set all of the weights of each control point in the resultGUI.apertureInfo.apertureVector to 0, except for the one that you're interested in. Do you know the structure of the apertureVector? If not I can give you more information on that.

Next I would update the apertureInfo and calculate the bixel weights:
`resultGUI.apertureInfo = matRad_daoVec2ApertureInfo(resultGUI.apertureInfo,resultGUI.apertureInfo.apertureVector);`

Next update the bixel weights in the resultGUI:
`resultGUI.w    = resultGUI.apertureInfo.bixelWeights;`

Finally, recalculate the dose:
`resultGUI = matRad_calcCubes(resultGUI.w,dij);`

**Comment by chh105** [comment]
@eric11210 thanks so much for the explanation. My only confusion right now is how the apertureVector is structured. For instance, right now I have a plan that has 120 control points and a 9436x1 apertureVector. If I just want to keep the contribution from control point 3, for example, which part of the apertureVector should I zero out

**Comment by eric11210** [comment]
If you have 120 independent (DAO) control points, then the first 120 elements of the apertureVector correspond to the weights of those control points, in order. The next big chunk correspond to the leaf positions, and at the end are the time intervals between control points.

So if you want to see the contribution from control point 3 only, then you would zero out all of the first 120 elements, except for the third element.

I would verify that this was done correctly by checking the results in the apertureInfo structure, after you've updated it using the line:
`resultGUI.apertureInfo = matRad_daoVec2ApertureInfo(resultGUI.apertureInfo,resultGUI.apertureInfo.apertureVector);`

**Comment by chh105** [comment]
So far I'm able to run everything except the matrad_calcCubes function without issue. When I run the matRad_calcCubes function, it asks for options.optBixel, and I'm not sure what that refers to. Is it part of some structure like the pln or resultGUI?

**Comment by wahln** [comment]
Also please consider that the function calls changed on the _merge version a little bit, as they are integrated into the object-oriented optimization framework now. I don't know which one you are using at the moment. I can update you on the syntax for this end of this week.

**Comment by chh105** [comment]
Thanks again. I'm currently using the dev_VMAT branch. After further inspection of the calcCubes and backProjection functions, I think that the options structure refers to the optimization options:
```
options.radMod          = pln.radiationMode;
options.bioOpt          = pln.propOpt.bioOptimization;
options.ID              = [pln.radiationMode '_' pln.propOpt.bioOptimization];
options.FMO             = false; % let optimizer know that this is FMO
options.numOfScenarios  = dij.numOfScenarios;
```
Also it seems like both backProjection and the calcCubes function produce the same dose distribution. Is there any reason why I should use one over the other in this case?

**Comment by eric11210** [comment]
No, I would expect both the produce the same dose distribution in this case. I think calcCubes actually calls backProjection, if I remember correctly.

**Comment by chh105** [comment]
Sure, sounds good. Also as a sanity check, I computed the physicalDose cubes for each control point, as well as the sum of all the dose cubes. The sum seems to be equivalent to the original overall dose distribution, so I think it's working. Is there any other sanity check I can try running?

**Comment by eric11210** [comment]
That's an excellent idea for a sanity check :)

Another thing to do might be a visual check. Try loading in an image of the dose for each control point, and verify that it looks like a beam coming in from the correct gantry angle, based on your VMAT arc settings.

**Comment by Sheipy** [comment]
Hello, I want to know whether we can do VMAT in MatRad right now. Is it released?

**Comment by eric11210** [comment]
Great! Let me know if you need any help with that.
